# Generated by Django 5.1.3 on 2024-11-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_attendancerecord_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='late_minutes',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='penalty_minutes',
            field=models.FloatField(default=0),
        ),
    ]
