# Generated by Django 5.1.3 on 2024-11-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_attendancerecord_penalty_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='penalty_minutes',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='annual_leave_days',
            field=models.FloatField(default=15),
        ),
    ]
